create table
  public."User" (
    id serial,
    "userId" text null,
    username text null,
    avatar text null,
    role integer null,
    platform text null,
    email text null,
    "subscriptionId" text null,
    "customerId" text null,
    "variantId" integer null,
    "currentPeriodEnd" integer null,
    "createdAt" timestamp without time zone not null default current_timestamp,
    "updatedAt" timestamp without time zone not null,
    "emailVerified" timestamp without time zone null,
    constraint User_pkey primary key (id)
  ) tablespace pg_default;

create unique index "User_userId_key" on public."User" using btree ("userId") tablespace pg_default;

create table
  public."Generate" (
    id bigint generated by default as identity,
    "createdAt" timestamp with time zone not null default now(),
    "updatedAt" timestamp with time zone null,
    generate bigint null default '0'::bigint,
    share bigint null default '0'::bigint,
    api bigint null,
    constraint Generate_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public._prisma_migrations (
    id character varying(36) not null,
    checksum character varying(64) not null,
    finished_at timestamp with time zone null,
    migration_name character varying(255) not null,
    logs text null,
    rolled_back_at timestamp with time zone null,
    started_at timestamp with time zone not null default now(),
    applied_steps_count integer not null default 0,
    constraint _prisma_migrations_pkey primary key (id)
  ) tablespace pg_default;